### ISSUE TITLE
Program not loading

### ISSUE THREAD

**Issue by Un1verstar** [tmglncc/CARTmath#1]
After executing each line of the code, the program gives an error when I run the program. It seems like I need to execute every library(...) line myself, since he doesn't find those files. How do I make this work? Also, when I execute the set working directory, the name automatically changes to CARTmath-master.

**Comment by tmglncc** [comment]
Hi, @Un1verstar! Could you tell us which operating system you are using and provide the error message that appears so that we can better assist you?

**Comment by Un1verstar** [comment]
Hi @tmglncc , I've already solved the issue. I didn't know you had to manually load all the library-commands. Thanks, the program looks fantastic! I'm a biomedical engineering student and I chose your review article to discuss, so it's always nice to have something interactive to demonstrate.

**Comment by tmglncc** [comment]
We are very happy that CAR**T**_math_ has been useful to you. Thanks for the feedback! If you have any problems, we are here to help you. We would also like to inform you that the CAR**T**_math_ online version is now available at `http://cartmath.lncc.br/`.
